version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_fire_alarm_system
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-fire_alarm_system}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Duong123}
    restart: unless-stopped
    networks:
      - fire-alarm-system

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: backend_fas
  #   ports:
  #     - "${SERVER_PORT:-8081}:8081"
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_DB=${POSTGRES_DB:-fire_alarm_system}
  #     - POSTGRES_USER=${POSTGRES_USER:-admin}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Duong123}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
  #     - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-604800000}
  #     - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
  #     - FIREBASE_SERVICE_ACCOUNT_KEY_PATH=${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}
  #   depends_on:
  #     - postgres
  #   restart: always
  #   networks:
  #     - fire-alarm-system

networks:
  fire-alarm-system:
    driver: bridge

volumes:
  postgres_data:
